import Head from 'next/head'
import Image from 'next/image'
import TodoApp from "./components/TodoApp"

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Supabase Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full justify-center items-center p-5 min-h-screen bg-custom-gradient">
        <TodoApp />
      </main>
    </>
  )
}
